<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>text</string>
    </array>
    <key>foldingStartMarker</key>
    <string>/\*\*|\{\s*$</string>
    <key>foldingStopMarker</key>
    <string>\*\*/|^\s*\}</string>
    <key>name</key>
    <string>zConsole</string>
    <key>patterns</key>
    <array>
        <dict> <!-- (In file included from )(/path/to/filename.ext):(123):(45), -->
            <key>name</key>
            <string>meta.block.error.cpp</string>
            <key>begin</key>
            <string>^((?:\w+ )*(.+\..{1,4}):(\d+):(\d+)[,:])</string>
            <key>beginCaptures</key> <!-- captures for the begin pattern -->
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>support.error.line.trail</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>string.unquoted</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>constant.numeric.integer</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>constant.numeric.integer</string>
                </dict>
            </dict>
            <key>end</key>
            <string>^(?: *(\^) *)$</string> <!--       ^      caret alone on the line  -->
            <key>captures</key> <!-- captures for the end pattern -->
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>support.indicator.caret</string>
                </dict>
            </dict>
            <key>patterns</key> <!-- patterns to capture within this block -->
            <array>
                <dict> <!-- #error string -->
                    <key>match</key>
                    <string>^(#(?:warning|error)) +(.*) *$</string>
                    <key>name</key>
                    <string>source.c</string>
                </dict>
                <dict> <!-- /path/to/filename.ext:123:45: warning: string -->
                    <key>match</key>
                    <string>(^.+\..{1,4}):(\d+):(\d+): ((warning|error|note): .+)$</string>
                    <key>name</key>
                    <string>support.error.line.trail</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>string.unquoted</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>constant.numeric.integer</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>constant.numeric.integer</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>meta.message.error</string>
                        </dict>
                    </dict>
                </dict>
                <dict> <!-- #error string -->
                    <key>match</key>
                    <string>^.*$</string>
                    <key>name</key>
                    <string>meta.error.line.source</string>
                </dict>
            </array>
        </dict>
        <dict> <!-- [ deviot x.x.x ] filename.ext -->
            <key>match</key>
            <string>(\[\s.+\s\]) ([\w]+\.[a-zA-Z]{3}$)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- [ deviot x.x.x ] string -->
            <key>match</key>
            <string>(\[\s.+\s\]) ([\w]+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- 00:00:00 string | status... -->
            <key>match</key>
            <string>(^[\d:]+)\s([a-zA-Z\s]+) \| ([[:alpha:]]+\.{3}$)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.numeric.time</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- 00:00:00 [INFO]: string(.) -->
            <key>match</key>
            <string>(^[\d:]+) \[INFO\]: ([[:alpha:]\s.]+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.numeric.time</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>
            </dict>
        </dict>
        <dict>  <!-- 00:00:00 string | STATE -->
            <key>match</key>
            <string>(^[\d:]+)\s([a-zA-Z\s]+) \| ([A-Z]+) \|</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.numeric.time</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- 00:00:00 string -->
            <key>match</key>
            <string>(^\d\d:\d\d:\d\d+) ([[:alpha:][0-9]_\.,\¡\!\s]*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.numeric.time</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>support.error.deviot</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- :00: string -->
            <key>match</key>
            <string>(.+\w+\.\w{3}):(\d+:*\d*:*) ([\w\s]+:) ()</string>
            <key>captures</key>
            <dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>            
            </dict>
        </dict>
        <dict> <!-- (file.ext): string -->
            <key>match</key>
            <string>(.+\(*\w+\.\w*\)*:) ([\w+\s]+)</string>
            <key>captures</key>
            <dict>                
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>            
            </dict>
        </dict>
        <dict> <!-- paths(file.ext): string -->
            <key>match</key>
            <string>( \w+:) ('\w+') ([\w+\s]+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict> 
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>         
            </dict>
        </dict>
        <dict> <!-- paths(file.ext): string -->
            <key>match</key>
            <string>:([\d+:]*)\s(\w+:)*</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict> 
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>         
            </dict>
        </dict>
        <dict> <!-- <mail@mail.xxx> -->
            <key>match</key>
            <string>.+ &lt;.+@.+&gt;.*</string>
            <key>name</key>
            <string>entity.name.class</string>
        </dict>
        <dict> <!-- Processing: string-->
            <key>match</key>
            <string>(Processing) (\w+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- string: string-->
            <key>match</key>
            <string>(\w+:) (\w+,)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- string: string digits bytes -->
            <key>match</key>
            <string>(^\w+:) (\w+) (\d+ bytes)\s([\w\s]+$)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- 'string': -->
            <key>match</key>
            <string>size:|address:</string>
            <key>name</key>
            <string>entity.name.function</string>
        </dict>
        <dict> <!-- string: string -->
            <key>match</key>
            <string>([Manually ]*\w+: )([\w+\.*\s]+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- alphanumeric .pioenvs -->
            <key>match</key>
            <string>([0-9\s]+) (\w+\s.pioenvs.*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- from digit to digit -->
            <key>match</key>
            <string>(from) (\w+) (to) (\w+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- string : string -->
            <key>match</key>
            <string>([\w+\s*]+)\s*:\s([\w+\.*\s*\w*]*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- avr header -->
            <key>match</key>
            <string>Block|Polled|Paged|#*Pages|Page|Poll|Memory|Type|Mode|Delay|Size|Indx|MinW|MaxW|ReadBack|AVR|Usage</string>
            <key>name</key>
            <string>entity.name.tag.xml</string>
        </dict>
        <dict> <!-- avr header -->
            <key>match</key>
            <string>(eeprom|flash|lfuse|hfuse|efuse|lock|calibration|signature)\s+(.+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- [STATUS] Took x.x seconds -->
            <key>match</key>
            <string>(\[[a-zA-Z]+\])\sTook\s([0-9]+\.[0-9]+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- string=alpha-->
            <key>match</key>
            <string>([-\w+]+)=(\w+\+*\w+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
            </dict>
        </dict>
        <dict> <!-- 'string': -->
            <key>match</key>
            <string>\\\"[\w+\s*]+\\\"\"*</string>
            <key>name</key>
            <string>entity.name.tag.xml</string>
        </dict>
        <dict> <!-- 'string': -->
            <key>match</key>
            <string>'.':*</string>
            <key>name</key>
            <string>entity.name.function</string>
        </dict>
        <dict> <!-- 'string': -->
            <key>match</key>
            <string>'\D+':*</string>
            <key>name</key>
            <string>entity.name.function</string>
        </dict>
        <dict> <!-- ^ -->
            <key>match</key>
            <string>^\^$</string>
            <key>name</key>
            <string>entity.name.tag.xml</string>
        </dict>
        <dict> <!-- only header -->
            <key>match</key>
            <string>^\[\s.+\s\]$</string>
            <key>name</key>
            <string>entity.name.class</string>
        </dict>
        <dict> <!-- status... -->
            <key>match</key>
            <string>[\w+\s+\/]+\.{3}$</string>
            <key>name</key>
            <string>entity.name.function</string>
        </dict>
        <dict> <!-- Compile Status -->
            <key>match</key>
            <string>^[[:alpha:]]+\s(?=\|)</string>
            <key>name</key>
            <string>storage.type</string>
        </dict>
        <dict> <!-- took time -->
            <key>match</key>
            <string>[\d\.\d]+s$</string>
            <key>name</key>
            <string>entity.name.class</string>
        </dict>
        <dict> <!-- : numbers -->
            <key>match</key>
            <string>\s\d+$</string>
            <key>name</key>
            <string>entity.name.class</string>
        </dict>
        <dict> <!-- address -->
            <key>match</key>
            <string>[\d+\.]+:\d+$</string>
            <key>name</key>
            <string>entity.name.class</string>
        </dict>
        <dict> <!-- address -->
            <key>match</key>
            <string>[a-zA-Z0-9-]+.local</string>
            <key>name</key>
            <string>entity.name.class</string>
        </dict>
        <dict> <!-- text data bss dec hex filename -->
            <key>match</key>
            <string>.+hex\sfilename</string>
            <key>name</key>
            <string>entity.name.function</string>
        </dict>
        <dict> <!-- digit ms -->
            <key>match</key>
            <string>[\d+]+\sms</string>
            <key>name</key>
            <string>entity.name.class</string>
        </dict>
        <!--
        <dict>  string 
            <key>match</key>
            <string>^[[:alpha:]\s\.]+$</string>
            <key>name</key>
            <string>entity.name.tag.xml</string>
        </dict>
        -->
    </array>
    <key>scopeName</key>
    <string>source.iot</string>
    <key>uuid</key>
    <string>bf85ce2a-4564-4863-8399-e8fce54f1dc1</string>
</dict>
</plist>
