<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>text</string>
    </array>
    <key>foldingStartMarker</key>
    <string>/\*\*|\{\s*$</string>
    <key>foldingStopMarker</key>
    <string>\*\*/|^\s*\}</string>
    <key>name</key>
    <string>zConsole</string>
    <key>patterns</key>
    <array>
        <dict> <!-- [ deviot x.x.x ] string -->
            <key>match</key>
            <string>(\[\s.+\s\]) ([[\w]+\s]+\.*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>src |lib |platformio.ini |Generating partitions|Compiling|Archiving|Updating|Uninstalling|Indexing|Downloading\.{3}|Unpacking\.{3}|Converting|Linking|Building|Calculating size|Collected|Processing|LibraryManager:|Library Storage:|\`[a-zA-Z\s\-\%\_\,\.]*\`*</string>
            <key>name</key>
            <string>entity.name.function</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(\S+:) (\S+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>(In function|error:) (\'[\S+\s]+\')</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>\[\S+\]</string>
            <key>name</key>
            <string>entity.name.class</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\@\s[[0-9]\.\:]+</string>
            <key>name</key>
            <string>entity.name.tag.xml</string>
        </dict>
        <dict>
            <key>match</key>
            <string>[a-zA-Z\-]+\s\@\s[[0-9]\.\:]+</string>
            <key>name</key>
            <string>entity.name.tag.xml</string>
        </dict>
        <dict> <!-- ^ -->
            <key>match</key>
            <string>^\^$</string>
            <key>name</key>
            <string>entity.name.tag.xml</string>
        </dict>
        <dict> <!-- took time -->
            <key>match</key>
            <string>(Took) ([\d\.*]+) </string>
            <key>name</key>
            <string>entity.name.class</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^[\d{2}]+[:*\d{2}]+</string>
            <key>name</key>
            <string>entity.name.class</string>
        </dict>
        <dict>
            <key>match</key>
            <string>text |data |bss |dec |hex |filename</string>
            <key>name</key>
            <string>entity.name.tag.xml</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.iot</string>
    <key>uuid</key>
    <string>bf85ce2a-4564-4863-8399-e8fce54f1dc1</string>
</dict>
</plist>
